### PR TITLE
added functionality to support multiple random bubble colors

### PR DESCRIPTION
**Pull request by Chappie74**
- `colorOfBubbles` field now changed to `colorsOfBubbles` and accepts a list of colors. 
- at least 1 color must be specified.

### CODE REVIEW

**Comment by Poujhit** [comment]
Let me check and will merge if no issues are there

**Comment by Chappie74** [comment]
Thanks. Let me know if there are any amendments I need to make before merge. 

I also have a random opacity change I will create a new PR for once this is merged.

**Comment by Poujhit** [comment]
Okay.

**Comment by Poujhit** [comment]
Merging this PR

**Comment by Poujhit** [comment]
Will release this change soon.

**Comment by Chappie74** [comment]
Hey @Poujhit, just checking in to remind you to publish the changes, just in case you might have forgotten.

**Comment by Poujhit** [comment]
Was caught up with something important. Will do it soon.

**Comment by Poujhit** [comment]
New version is released. @Chappie74

**Comment by Chappie74** [comment]
thank you

**Pull request merged**
